Fix build failure related to `#include` in `master.c`
In `master/master.c`, fix includes to pick up excluded declarations.
Kernel header structure may have changed in more recent distros; the
following (incomplete) list of errors was observed on Ubuntu Trusty
14.04:

    /var/lib/dkms/etherlabmaster/1.5~git20190614.1+gl20190904.1+mds20210617.1/build/master/master.c: In function ‘set_normal_priority’:
    /var/lib/dkms/etherlabmaster/1.5~git20190614.1+gl20190904.1+mds20210617.1/build/master/master.c:1776:12: error: variable ‘param’ has initializer but incomplete type
         struct sched_param param = { .sched_priority = 0 };
                ^
    /var/lib/dkms/etherlabmaster/1.5~git20190614.1+gl20190904.1+mds20210617.1/build/master/master.c:1776:12: error: unknown field ‘sched_priority’ specified in initializer
    /var/lib/dkms/etherlabmaster/1.5~git20190614.1+gl20190904.1+mds20210617.1/build/master/master.c:1776:12: warning: excess elements in struct initializer [enabled by default]
    /var/lib/dkms/etherlabmaster/1.5~git20190614.1+gl20190904.1+mds20210617.1/build/master/master.c:1776:12: warning: (near initialization for ‘param’) [enabled by default]
    /var/lib/dkms/etherlabmaster/1.5~git20190614.1+gl20190904.1+mds20210617.1/build/master/master.c:1776:24: error: storage size of ‘param’ isn’t known
         struct sched_param param = { .sched_priority = 0 };
                            ^
    /var/lib/dkms/etherlabmaster/1.5~git20190614.1+gl20190904.1+mds20210617.1/build/master/master.c:1776:24: warning: unused variable ‘param’ [-Wunused-variable]

In `update-ethercat-config`, handle case when systemd not available.